<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Prakerin | PT Sumber Alfaria Trijaya, Tbk</title>
    <?php 
    echo $this->headLink();
    echo $this->headScript();
    ?>
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/signin.css'); ?>" type="text/css" />
</head>
<body>
    <?php 
    $session = new Zend_Session_Namespace('prakerin');
    echo $this->layout()->content;
    
    $message = $this->message;
    
    if ($message <> '') {
        
    }
    ?>
</body>
</html>