<!DOCTYPE html>
<html>
	<head>
	  	<meta charset="utf-8">
	  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	  	<title>Prakerin | PT Sumber Alfaria Trijaya, Tbk</title>
	  	<meta name="description" content="">
    	<meta name="author" content="">
    
	  	<!-- Tell the browser to be responsive to screen width -->
	  	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	  
	  	<?php $session = new Zend_Session_Namespace('prakerin'); ?>
	  	<?php echo $this->headLink(); ?>
	  	<?php echo $this->headScript(); ?>
	    
	  	<!-- Google Font -->
	  	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
	</head>
	<body class="hold-transition skin-blue sidebar-mini">
	<div class="wrapper">
		<?php $globalSession = new Zend_Session_Namespace('humancapital'); ?>
	  <header class="main-header">
	    <!-- Logo -->
	    <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'),'',true);?>" class="logo">
	      <!-- mini logo for sidebar mini 50x50 pixels -->
	      <span class="logo-mini"><b>P</b></span>
	      <!-- logo for regular state and mobile devices -->
	      <span class="logo-lg"><b>Prakerin</b></span>
	    </a>
	    <!-- Header Navbar: style can be found in header.less -->
	    <nav class="navbar navbar-static-top">
	      <!-- Sidebar toggle button-->
	      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
	        <span class="sr-only">Toggle navigation</span>
	      </a>
	
	      <div class="navbar-custom-menu">
	        <ul class="nav navbar-nav">
	          
	          
	        </ul>
	      </div>
	    </nav>
	  </header>
	  
	  
	  <!-- Left side column. contains the logo and sidebar -->
	  <aside class="main-sidebar">
	    <!-- sidebar: style can be found in sidebar.less -->
	    <section class="sidebar">
	      <!-- Sidebar user panel -->
	      <div class="user-panel">
	        <div class="pull-left image">
	          <img src="<?php echo $this->baseUrl('admin-lte/img/avatar5.png');?>" class="img-circle" alt="User Image">
	        </div>
	        <div class="pull-left info">
	          <p>Alexander Pierce</p>
	          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
	        </div>
	      </div>
	      <!-- search form -->
	      <form action="#" method="get" class="sidebar-form">
	        <div class="input-group">
	          <input type="text" name="q" class="form-control" placeholder="Search...">
	          <span class="input-group-btn">
	                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
	                </button>
	              </span>
	        </div>
	      </form>
	      <!-- /.search form -->
	      <!-- sidebar menu: : style can be found in sidebar.less -->
	      <ul class="sidebar-menu" data-widget="tree">
	        <li class="header">MAIN NAVIGATION</li>
	        
	        <!-- Human Capital Application -->
	     	<li class="treeview">
	          <a href="#">
	            <i class="fa fa-dashboard"></i> <span>Intranet</span>
	            <span class="pull-right-container">
	              <i class="fa fa-angle-left pull-right"></i>
	            </span>
	          </a>
	          <ul class="treeview-menu">
	          	<?php if(!empty($globalSession) && is_array($globalSession->menus)) { ?>
	          	<?php 	foreach($globalSession->menus as $menu) { ?>
	          	<?php 		 echo '<li><a href="'.$menu['PROJECT'].'">'.$menu['DESKRIPSI'].'</a></li>'; ?>
	          	<?php 	} ?>
	          	<?php } ?>
	          </ul>
	        </li>
	        
	        
	        <li class="active treeview">
	          <a href="#">
	            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
	            <span class="pull-right-container">
	              <i class="fa fa-angle-left pull-right"></i>
	            </span>
	          </a>
	          <ul class="treeview-menu">
	            <li class="active"><a href="#"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
	            <li><a href="#"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
	          </ul>
	        </li>
	        <li>
	          <a href="pages/widgets.html">
	            <i class="fa fa-th"></i> <span>Widgets</span>
	            <span class="pull-right-container">
	              <small class="label pull-right bg-green">new</small>
	            </span>
	          </a>
	        </li>
	        
	      </ul>
	    </section>
	    <!-- /.sidebar -->
	  </aside>
	
	  <!-- Content Wrapper. Contains page content -->
	  <div class="content-wrapper">
	  
	    <!-- Content Header (Page header) -->
	    <section class="content-header">
	      <h1>
	        Dashboard
	        <small>Control panel</small>
	      </h1>
	      <ol class="breadcrumb">
	        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
	        <li class="active">Dashboard</li>
	      </ol>
	    </section>
	    <?php $session->messageAlert = array('msg'=>"ini pesannya !", "status", "danger"); ?>
	    
	    <section class="content">
	    	<div class="row">
	    		<div class="col-md-12">
		    		<?php if(isset($session->messageAlert) && sizeof($session->messageAlert) > 1) {?>
			    	<?php 	if(isset($session->messageAlert['msg']) && $session->messageAlert['msg'] != "") { ?>
			    	<div class="alert alert-<?php echo isset($session->messageAlert['status']) ? ($session->messageAlert['status'] != "" ? $session->messageAlert['status'] : "danger" ) : "danger";?>" role="alert" >
			    		<span style="color: black;"><?php echo $session->messageAlert['msg']; ?></span>
			    	</div>
			    	<?php 	} ?>
			    	<?php } ?>
	    		</div>
	    	</div>
	    	<div class="row">
		    	<div class="col-md-12">
		    		<?php echo $this->layout()->content; ?>
		    	</div>
		    </div>
	    </section>
	    
	    
	  </div>
	  <!-- /.content-wrapper -->
	  <footer class="main-footer">
	    <strong>Copyright &copy; 2017 PT Sumber Alfaria Trijaya</strong>
	  </footer>
	  
	  <!-- copyright &copy; 2014-2016 Almsaeed Studio, https://adminlte.io -->
	
	 
	  <!-- Add the sidebar's background. This div must be placed immediately after the control sidebar -->
	  <div class="control-sidebar-bg"></div>
	</div>
	<!-- ./wrapper -->
	
	
	</body>
</html>
